- name: Generic PRE-TASK Playbook
  hosts: vm
  become: yes
  gather_facts: yes
  vars_files:
  pre_tasks:
    - name: Generic PRE Tasks
      ansible.builtin.import_tasks: ./generic_pre_tasks.yml

  tasks:
    - name: Setting up your virtual machine
      block:
      always:

  post_tasks:
    - name: Generic POST Tasks
      ansible.builtin.import_tasks: ./generic_post_tasks.yml
