services:
  simplevm-client-giessen:
    container_name: simplevm-client-giessen
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${CLIENT_PORT}:9091
    env_file:
      - .env.dev.giessen
    environment:
      - TERM=xterm-256color
    tty: true
    volumes:
      - ./simple_vm_client/config/config_giessen.yml:/code/simple_vm_client/config.yml
      - ./simple_vm_client/keys/localhost/server.pem:/code/simple_vm_client/keys/server.pem
    command: python3 VirtualMachineServer.py /code/simple_vm_client/config.yml
    networks:
      - portal

  simplevm_client_giessen_redis:
    container_name: simplevm_client_giessen_redis
    image: redis:8.8.0@sha256:234c902a2db49461a129e2d4aeff85b28cf20187ed274a67f6e50995fa713c7b
    expose:
      - "6379"
    networks:
      - portal

  simplevm_metadata_server:
    container_name: simplevm_metadata_server
    image: oci.bi.denbi.de/simplevm/simplevm-metadata-server:2.0.4@sha256:3a214d29012d0937fe7366b5ff4fed2e7481679bb400a59c5718c7939b49c4d3
    ports:
      - "8008:8008"
    depends_on:
      - simplevm_metadata_server_redis
    environment:
      - METADATA_WRITE_TOKEN
      - METADATA_PORT=8008
      - METADATA_HOST=0.0.0.0
    networks:
      - portal
    restart: unless-stopped

networks:
  portal:
    name: portal
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1440
