FROM python:3.13.4
WORKDIR /code

# Copy all requirements files at once
COPY requirements*.txt /code/

# Install all dependencies in one step
RUN pip install -r requirements.txt -r requirements-test.txt

# Copy the entire project
COPY . /code

WORKDIR /code/simple_vm_client
CMD ["python", "-m", "coverage", "run", "-m", "pytest"]
