FROM python:3.14.7@sha256:8edbf9e42c7fb168b9c523718ed907117e6d2e60f5889c0c499bbda3a787da53
WORKDIR /code

# Copy all requirements files at once
COPY requirements*.txt /code/

# Install all dependencies in one step
RUN pip install -r requirements.txt -r requirements-test.txt

# Copy the entire project
COPY . /code

WORKDIR /code/simple_vm_client
CMD ["python", "-m", "coverage", "run", "-m", "pytest"]
