redis:
  host: simplevm_client_giessen_redis
  port: 6379
  password: ""

production: False

logger:
  level: INFO
  file: log/portal_client.log
  file_backup_count: 5
  max_bytes: 1073741824

server:
  threads: 30
  host: 0.0.0.0
  port: 9090
  # If you use docker-compose this path needs to be the path you mount the server.pem into
  certfile: /code/VirtualMachineService/keys/server.pem
  use_ssl: False

openstack:
  cloud_site: giessen
  gateway_security_group_id: b9ccddab-7e17-4df5-8282-48fd593500a8
  host: 0.0.0.0
  # Client Port
  port: 9090
  # Gateway IP
  gateway_ip: 134.176.27.238

  # If set to True the client will use a Gateway instead of providing floating IPs for each instance.
  use_gateway: True

  set_password: False
  # network where the project is located
  network: SimpleVMGieTest-Netzwerk

  # subnetwork for starting Clusters
  sub_network: SimpleVMGieTest-Subnetz

  ssh_port_calculation: 30000 + x + y * 256
  udp_port_calculation: 30000 + x + y * 256

cloud_site: giessen


bibigrid:
  # Url for Bibigrid API
    port: 8080
    host: simplevm_bibigrid
    https: False
    sub_network: portalexternalsubnetwork
    modes:
      -   slurm
forc:
  forc_url: https://proxy-dev.gi.denbi.de:4443/
  github_playbooks_repo: https://github.com/deNBI/resenvs/archive/refs/heads/staging.zip
  forc_security_group_id: 5adb9f48-1e57-463b-9742-573ba2dabae2
