production: False



redis:
  host: simplevm_client_redis
  port: 6379
  password: ""


server:
  threads: 30
  host: 0.0.0.0
  port: 9090
  # If you use docker-compose this path needs to be the path you mount the server.pem into
  certfile: /code/VirtualMachineService/keys/server.pem
  use_ssl: True



openstack:
  gateway_security_group_id:  88b530b3-0b62-4edc-b5f6-d80fbbba0830
  cloud_site: bielefeld
  #Calculation for Ports - 30000 Base Port (192.168.1.20 - 1 = y , 20 =x)
  ssh_port_calculation: 30000 + x + y * 256
  udp_port_calculation: 30000 + x + y * 256


  # Gateway IP
  gateway_ip: 129.70.51.75
  # If set to True the client will use a Gateway instead of providing floating IPs for each instance.
  use_gateway: True

  set_password: False
  # network where the project is located
  network: portalexternalnetwork

  # subnetwork for starting Clusters
  sub_network: portalexternalsubnetwork

  production: False


  floating_ip_network: external

  # If you use docker-compose this path needs to be the path you mount the server.pem into
  certfile: /code/VirtualMachineService/keys/server.pem
  use_ssl: True

bibigrid:
  # Url for Bibigrid API
    port: 8080
    host: bibigrid
    https: False
    sub_network: portalexternalsubnetwork
    modes:
      -   slurm

forc:
  forc_url: https://proxy-dev.bi.denbi.de:5000/
  github_playbooks_repo: https://github.com/deNBI/resenvs/archive/refs/heads/staging.zip
  forc_security_group_id: forc_security_group_id
