production: False


redis:
  host: simplevm_client_redis
  port: 6379
  password: ""

logger:
  level: INFO
  file: log/portal_client.log
  file_backup_count: 5
  max_bytes: 1073741824

server:
  threads: 30
  host: 0.0.0.0
  port: 9090
  # If you use docker-compose this path needs to be the path you mount the server.pem into
  certfile: /code/VirtualMachineService/keys/server.pem
  use_ssl: False

openstack:

  gateway_security_group_id: 88b530b3-0b62-4edc-b5f6-d80fbbba0830
  cloud_site: bielefeld
  #Calculation for Ports - 30000 Base Port (192.168.1.20 - 1 = y , 20 =x)
  ssh_port_calculation: 30000 + x + y * 256
  udp_port_calculation: 30000 + x + y * 256


  # Gateway IP
  gateway_ip: 129.70.51.75
  # If set to True the client will use a Gateway instead of providing floating IPs for each instance.
  use_gateway: True

  set_password: False
  # network where the project is located
  network: portalexternalnetwork

  # subnetwork for starting Clusters
  sub_network: portalexternalsubnetwork


  floating_ip_network: external


  # Used for gateway port calculation , x is always the last octet of the fixed ip (example : (x + 3) *3 ) )
  ssh_port_calc_formular: 30000 + x
  udp_port_calc_formular: x * 10 +  30000

bibigrid:
  # Url for Bibigrid API
  port: 8080
  host: simplevm_bibigrid
  https: False
  localDnsLookup: False
  sub_network: portalexternalsubnetwork
  modes:
    - slurm
  ansibleGalaxyRoles:
    - name: autoscaling
      hosts: master
      git: https://github.com/patricS4/autoscaling-config-ansible

forc:
  forc_url: https://proxy-dev.bi.denbi.de:5000/
  forc_access_url: https://proxy-dev.bi.denbi.de/
  github_playbooks_repo: https://github.com/deNBI/resenvs/archive/refs/heads/staging.zip
  forc_security_group_id: 9a08eecc-d9a5-405b-aeda-9d4180fc94d6

cloud_site: bielefeld
